[acoustics]
n_fft = 512
win_length = 512
sr = 16000
hop_length = 256


[inferencer]
path = "inter_subnet.inferencer.inferencer.Inferencer"
type = "full_band_crm_mask"

[inferencer.args]
n_neighbor = 15


[dataset]
path = "inter_subnet.dataset.dataset_inference.Dataset"
[dataset.args]
dataset_dir_list = [
    "/workspace/project-nas-11025-sh/speech_enhance/data/DNS-Challenge/DNS-Challenge-interspeech2020-master/datasets/test_set/synthetic/with_reverb/noisy"
    # "/workspace/project-nas-11025-sh/speech_enhance/data/DNS-Challenge/DNS-Challenge-interspeech2020-master/datasets/test_set/synthetic/no_reverb/noisy"
]
sr = 16000


[model]
path = "inter_subnet.model.Inter_SubNet.Inter_SubNet"
[model.args]
sb_num_neighbors = 15
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
sb_output_activate_function = false
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2
sbinter_middle_hidden_times = 0.8

